using System.IO;

namespace WurstModCodeGen.ResourceGenerators
{
    public abstract class ResourceGenerator
    {
        /// <summary>
        ///     The number of files that have been passed to this generator
        /// </summary>
        public int ScannedFiles { get; private set; }
        
        /// <summary>
        ///     The name of this resource generator
        /// </summary>
        public abstract string Name { get; }
        
        /// <summary>
        ///     Just a wrapper around the other Discovered method that also increments a counter.
        /// </summary>
        /// <param name="filePath">Path of the discovered file</param>
        public void Discovered(string filePath)
        {
            ScannedFiles++;
            Discovered(new FileInfo(filePath));
        }
        
        /// <summary>
        ///     This is called when a file of a matching type is discovered
        /// </summary>
        /// <param name="file">The discovered file</param>
        protected abstract void Discovered(FileInfo file);

        /// <summary>
        ///     This is called once all the files have been iterated over.
        /// </summary>
        /// <returns>Returns a string representing the code generated by this generator</returns>
        public abstract string Generate();
    }
}